version: '3.8'

services:
  app:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  mongo-client:
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://db:27017

volumes:
  mongo_data:
  # minio_data: