version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./images:/app/images
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
      - JWT_SECRET_KEY=your-secret-key
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
